### ISSUE TITLE
what is the meaning of “chunks”？

### ISSUE THREAD

**Issue by ysmhyl** [NVlabs/STEP#15]
thank U for  sharing first! I try to understand the meaning of "chunks"?is it related to "T"? Look foraward to your reply!
`    for i in range(1, exec_iter+1):    # index from 1
        # adaptively get the start chunk
        chunks = args.NUM_CHUNKS[i]
        T_start = int((args.NUM_CHUNKS[args.max_iter] - chunks) / 2) * args.T
        T_length = chunks * args.T
        chunk_idx = [j*args.T + int(args.T/2) for j in range(chunks)]    # used to index the middel frame of each chunk
        half_T = int(args.T/2)`

**Comment by xyang35** [comment]
Thanks for your interest in our work! The "chunks" basically means the "tubelet" in the [teaser figure](https://github.com/NVlabs/STEP/blob/master/teaser.jpg). As STEP involves a progressive temporal extension step, it would gradually incorporate more temporal context by increasing the length of the input tubelet, which is implemented as using more connected "chunks" in time. For example, if chunks = 3, then the length of the input tubelet would be 3*T.
