### ISSUE TITLE
AVA Evaluation

### ISSUE THREAD

**Issue by tomanick** [NVlabs/STEP#7]
Thanks for your nice github!
I want to run the evaluation for the AVA dataset.
But I don't know the format of the result.csv .
Could you give me the example of the result.csv which your codes want?
I just want to know the format of the result.csv of prediction. Ex: video name, scores, label and so on.
Thank you!

**Comment by xyang35** [comment]
Thanks for your interest in our work! The result should have the same format as the submission format for the ActivityNet challenge (http://activity-net.org/challenges/2019/tasks/guest_ava.html), i.e., `video_id, middle_frame_timestamp, person_box, action_id, score`.

**Comment by NaeemKhan333** [comment]
How can custom dataset can be converted to AVA-Dataset format, can you guide me about this?
